from __future__ import annotations

PREMIUM_CATALOG = {
    "midnight-jazz": {
        "title": "Midnight Jazz Muse",
        "collection": "Midnight Jazz",
        "difficulty": "Expert",
        "colors": 28,
        "target_regions": 560,
        "min_region_area": 24,
        "description": "A joyful saxophone performance beneath a luminous midnight skyline.",
    },
    "noir-vinyl": {
        "title": "Noir Vinyl Reverie",
        "collection": "Analog Dreams",
        "difficulty": "Advanced",
        "colors": 24,
        "target_regions": 480,
        "min_region_area": 28,
        "description": "Graphic black-and-cream vinyl artwork with strong rhythmic detail.",
    },
    "afrofuturist-stargazer": {
        "title": "Afrofuturist Stargazer",
        "collection": "Celestial Heritage",
        "difficulty": "Expert",
        "colors": 30,
        "target_regions": 600,
        "min_region_area": 22,
        "description": "A luminous cosmic portrait filled with stars, color, and wonder.",
    },
    "golden-koi": {
        "title": "Golden Koi & Lotus",
        "collection": "Serenity",
        "difficulty": "Advanced",
        "colors": 26,
        "target_regions": 540,
        "min_region_area": 22,
        "description": "Ornamental koi and lotus artwork with flowing line detail.",
    },
    "rainy-cafe": {
        "title": "Rainy Café Nocturne",
        "collection": "Rain & Reflection",
        "difficulty": "Expert",
        "colors": 30,
        "target_regions": 620,
        "min_region_area": 20,
        "description": "A glowing café street scene reflected across a rainy evening.",
    },
    "botanical-portrait": {
        "title": "Celestial Botanical Portrait",
        "collection": "Botanical Muses",
        "difficulty": "Expert",
        "colors": 30,
        "target_regions": 600,
        "min_region_area": 20,
        "description": "A richly decorated floral portrait framed by moons and stars.",
    },
    "art-deco-peacock": {
        "title": "Art Deco Peacock",
        "collection": "Gilded Geometry",
        "difficulty": "Expert",
        "colors": 28,
        "target_regions": 620,
        "min_region_area": 18,
        "description": "A jewel-toned peacock surrounded by intricate gilded ornament.",
    },
    "brownstone-jazz": {
        "title": "Brownstone Jazz Evening",
        "collection": "Urban Heritage",
        "difficulty": "Expert",
        "colors": 30,
        "target_regions": 650,
        "min_region_area": 18,
        "description": "A vibrant outdoor jazz ensemble illuminated by warm brownstone lights.",
    },
}
